export const DEFAULT_LOCALE = "en";
export const SUPPORTED_LOCALES = ["en", "zh"];

export const siteCopyByLocale = {
  en: {
    intro: {
      name: "SiCheng Chen",
      title: "Technical Artist / Environment",
      bio: "Based in Chengdu, China | Remote Status: Worldwide Remote (B2B / Contractor) | Available for Timezone Overlap (EU/US/APAC)",
      bioSecondary: "Technical Artist (5+ years) specializing in UE5 and Unity. I build high-fidelity, performant environments using Houdini procedural pipelines, shaders, and production tools (C++/Python/Blueprint).",
      contact: {
        email: "chensicheng0608@outlook.com",
        phone: "+86 15553331116",
        city: "Chengdu, China",
      },
      skillGroups: [
        { label: "Game Engines", items: ["Unreal Engine 5", "Unity"] },
        { label: "Technical Art", items: ["Blueprints", "C++", "HLSL / GLSL"] },
        { label: "Procedural & Tools", items: ["Houdini"] },
        { label: "Scripting", items: ["Python", "C#"] },
        { label: "Environment Art", items: ["Environment Art", "Lighting", "Materials/Shader", "Optimization"] },
        { label: "DCC Tools", items: ["Blender", "Substance Painter", "Substance Designer", "Photoshop"] },
      ],
      socials: [],
      scrollHint: "SCROLL",
    },
    works: {
      sectionTitle: "Works",
      tabs: [
        { id: "full-game", label: "FULL GAME PROJECT EXPERIENCE" },
        { id: "demos", label: "GAME DEMOS" },
        { id: "tools", label: "TOOLS / FEATURES" },
        { id: "shader", label: "SHADER / VFX / MODEL" },
      ],
      emptyStateTitle: "Create your first work in this category",
      emptyStateCta: "+",
      createNow: "CREATE NOW",
      viewDetails: "VIEW DETAILS",
      tabAriaLabel: "Work categories",
    },
    music: {
      enablePrompt: "Click to enable sound",
      muteLabel: "Mute",
      unmuteLabel: "Unmute",
      soundOff: "Sound off",
      nowPlaying: "Now playing",
      paused: "Paused",
      volumeLabel: "Background music volume",
      switchToChinese: "中文",
      switchToEnglish: "EN",
      languageToggleLabel: "Switch language",
    },
    common: {
      workNotFound: "Work not found.",
      backHome: "Back Home",
      back: "Back",
      edit: "Edit",
      createWork: "Create Work",
      createWorkDesc: "Build a new portfolio entry with structured blocks.",
      editWork: "Edit Work",
      editWorkDesc: "Update project content and structure.",
    },
  },
  zh: {
    intro: {
      name: "陈思成",
      title: "技术美术 / 场景",
      bio: "坐标成都 | 远程状态：全球远程（B2B / 外包合作）| 支持时区重叠协作（欧洲/美洲/亚太）",
      bioSecondary: "技术美术师（5年+经验），专注于 UE5 和 Unity。我使用 Houdini 程序化流程、着色器以及生产工具（C++/Python/Blueprint）构建高保真、高性能的游戏场景。",
      contact: {
        email: "chensicheng0608@outlook.com",
        phone: "+86 15553331116",
        city: "中国 成都",
      },
      skillGroups: [
        { label: "游戏引擎", items: ["Unreal Engine 5", "Unity"] },
        { label: "技术美术", items: ["Blueprints", "C++", "HLSL / GLSL"] },
        { label: "程序化 & 工具", items: ["Houdini"] },
        { label: "脚本", items: ["Python", "C#"] },
        { label: "场景美术", items: ["场景美术", "灯光", "材质/着色器", "优化"] },
        { label: "DCC 工具", items: ["Blender", "Substance Painter", "Substance Designer", "Photoshop"] },
      ],
      socials: [],
      scrollHint: "下滑浏览",
    },
    works: {
      sectionTitle: "作品",
      tabs: [
        { id: "full-game", label: "完整游戏项目经验" },
        { id: "demos", label: "游戏 Demo" },
        { id: "tools", label: "工具 / 功能" },
        { id: "shader", label: "着色器 / 特效 / 模型" },
      ],
      emptyStateTitle: "当前分类还没有作品，立即创建第一条吧",
      emptyStateCta: "+",
      createNow: "立即创建",
      viewDetails: "查看详情",
      tabAriaLabel: "作品分类",
    },
    music: {
      enablePrompt: "点击启用声音",
      muteLabel: "静音",
      unmuteLabel: "取消静音",
      soundOff: "声音已关闭",
      nowPlaying: "正在播放",
      paused: "已暂停",
      volumeLabel: "背景音乐音量",
      switchToChinese: "中文",
      switchToEnglish: "EN",
      languageToggleLabel: "切换语言",
    },
    common: {
      workNotFound: "未找到该作品。",
      backHome: "返回首页",
      back: "返回",
      edit: "编辑",
      createWork: "新建作品",
      createWorkDesc: "使用结构化内容块创建新的作品条目。",
      editWork: "编辑作品",
      editWorkDesc: "更新作品内容与结构。",
    },
  },
};
